language: php

php:
    - 5.5
    - 7.0

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=strict

matrix:
    fast_finish: true

before_install:
    - composer selfupdate

install:
    - composer update --prefer-dist --no-interaction

script:
    - ./bin/console doctrine:database:create --env=test
    - ./bin/console doctrine:schema:create --env=test
    - ./bin/console doctrine:fixtures:load --env=test --no-interaction
    - phpunit
