easy_admin:
    site_name: 'ACME Backend'
    entities:
        Category: AppBundle\Entity\Category
        Image: AppBundle\Entity\Image
        Purchase: AppBundle\Entity\Purchase
        PurchaseItem:
            class: AppBundle\Entity\PurchaseItem
            label: 'Purchase Item'
        Product:
            class: AppBundle\Entity\Product
            list:
                fields:
                    - id
                    - name
                    - { property: 'price', format: '%.2f' }
                    - { property: 'ean', label: 'EAN13', type: 'string' }
                    - enabled
                    - { property: 'createdAt', format: 'j / M / Y' }
                    - tags
            show:
                fields:
                    - id
                    - name
                    - { property: 'ean', type: 'string' }
                    - description
                    - price
                    - features
                    - enabled
                    - createdAt
            form:
                fields:
                    - { property: name, class: 'input-lg' }
                    - { property: price, type: 'number', help: 'Prices are always in euros' }
                    - { property: 'ean', label: 'EAN', help: 'EAN 13 valid code. Leave empty if unknown.' }
                    - enabled
                    - description
