easy_admin:
    entities:
        - AppBundle\Entity\Category
        - AppBundle\Entity\Image
        - AppBundle\Entity\Order
        - AppBundle\Entity\OrderItem
        - AppBundle\Entity\Product
