_homepage:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: admin, permanent: true }

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: @AppBundle/Controller/
    type:     annotation
