security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        users:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        main:
            pattern: ^/
            provider: users
            anonymous: ~
